-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_Customer" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "templateId" TEXT,
    "name" TEXT NOT NULL DEFAULT '',
    "email" TEXT NOT NULL DEFAULT '',
    "status" TEXT NOT NULL DEFAULT 'active',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "brideNick" TEXT NOT NULL DEFAULT 'Sophia',
    "groomNick" TEXT NOT NULL DEFAULT 'Alexander',
    "dateText" TEXT NOT NULL DEFAULT 'Saturday, October 24th, 2026',
    "countdownMaster" TEXT NOT NULL DEFAULT '2026-10-24T10:00',
    "coupleTitle" TEXT NOT NULL DEFAULT 'Two Souls, One Heart',
    "coupleSub" TEXT NOT NULL DEFAULT 'We invite you to share in our joy as we exchange our vows and begin our new life together.',
    "groomFull" TEXT NOT NULL DEFAULT 'Alexander Pierce',
    "groomRole" TEXT NOT NULL DEFAULT 'The Groom',
    "groomPhoto" TEXT NOT NULL DEFAULT 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80',
    "groomDad" TEXT NOT NULL DEFAULT 'Mr. Robert Pierce',
    "groomMom" TEXT NOT NULL DEFAULT 'Mrs. Elena Pierce',
    "brideFull" TEXT NOT NULL DEFAULT 'Sophia Laurent',
    "brideRole" TEXT NOT NULL DEFAULT 'The Bride',
    "bridePhoto" TEXT NOT NULL DEFAULT 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    "brideDad" TEXT NOT NULL DEFAULT 'Mr. Arthur Laurent',
    "brideMom" TEXT NOT NULL DEFAULT 'Mrs. Clara Laurent',
    "verseText" TEXT NOT NULL DEFAULT '"And above all these put on love, which binds everything together in perfect harmony."',
    "verseSource" TEXT NOT NULL DEFAULT 'Colossians 3:14',
    "storyDate1" TEXT NOT NULL DEFAULT 'June 2018',
    "storyTitle1" TEXT NOT NULL DEFAULT 'First Meeting',
    "storyDesc1" TEXT NOT NULL DEFAULT 'We met at a small coffee shop in the city.',
    "storyDate2" TEXT NOT NULL DEFAULT 'Dec 2024',
    "storyTitle2" TEXT NOT NULL DEFAULT 'The Proposal',
    "storyDesc2" TEXT NOT NULL DEFAULT 'Under the stars, a promise was made to last forever.',
    "akadDate" TEXT NOT NULL DEFAULT 'Saturday, October 24, 2026',
    "akadTime" TEXT NOT NULL DEFAULT '08:00 AM - 10:00 AM',
    "akadPlace" TEXT NOT NULL DEFAULT 'Grand Heritage Mosque',
    "resepsiDate" TEXT NOT NULL DEFAULT 'Saturday, October 24, 2026',
    "resepsiTime" TEXT NOT NULL DEFAULT '07:00 PM - End',
    "resepsiPlace" TEXT NOT NULL DEFAULT 'The Ritz-Carlton Ballroom',
    "gal1" TEXT NOT NULL DEFAULT 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=400&q=80',
    "gal2" TEXT NOT NULL DEFAULT 'https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=400&q=80',
    "gal3" TEXT NOT NULL DEFAULT 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?auto=format&fit=crop&w=400&q=80',
    "gal4" TEXT NOT NULL DEFAULT 'https://images.unsplash.com/photo-1606800052052-a08af7148866?auto=format&fit=crop&w=400&q=80',
    "gal5" TEXT NOT NULL DEFAULT 'https://images.unsplash.com/photo-1520854221256-17451cc331bf?auto=format&fit=crop&w=400&q=80',
    "gal6" TEXT NOT NULL DEFAULT 'https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?auto=format&fit=crop&w=400&q=80',
    "rsvpTitle" TEXT NOT NULL DEFAULT 'Will You Join Us?',
    "rsvpDesc" TEXT NOT NULL DEFAULT 'Please kindly confirm your attendance by October 1st, 2026.',
    "bankName" TEXT NOT NULL DEFAULT 'BCA',
    "bankAcc" TEXT NOT NULL DEFAULT '1234567890',
    "bankHolder" TEXT NOT NULL DEFAULT 'Alexander Pierce',
    "streamTitle" TEXT NOT NULL DEFAULT 'Virtual Wedding',
    "streamDesc" TEXT NOT NULL DEFAULT 'For friends and family who cannot attend physically, join our special day virtually.',
    "wishesTitle" TEXT NOT NULL DEFAULT 'Guest Book',
    "wishesDesc" TEXT NOT NULL DEFAULT 'Leave your warmest wishes and blessings for our marriage.',
    "closingThanks" TEXT NOT NULL DEFAULT 'Terima Kasih',
    "closingFam" TEXT NOT NULL DEFAULT 'The Pierce & Laurent Families'
);
INSERT INTO "new_Customer" ("akadDate", "akadPlace", "akadTime", "bankAcc", "bankHolder", "bankName", "brideDad", "brideFull", "brideMom", "brideNick", "bridePhoto", "brideRole", "closingFam", "closingThanks", "countdownMaster", "coupleSub", "coupleTitle", "createdAt", "dateText", "gal1", "gal2", "gal3", "gal4", "gal5", "gal6", "groomDad", "groomFull", "groomMom", "groomNick", "groomPhoto", "groomRole", "id", "name", "resepsiDate", "resepsiPlace", "resepsiTime", "rsvpDesc", "rsvpTitle", "status", "storyDate1", "storyDate2", "storyDesc1", "storyDesc2", "storyTitle1", "storyTitle2", "streamDesc", "streamTitle", "templateId", "updatedAt", "verseSource", "verseText", "wishesDesc", "wishesTitle") SELECT "akadDate", "akadPlace", "akadTime", "bankAcc", "bankHolder", "bankName", "brideDad", "brideFull", "brideMom", "brideNick", "bridePhoto", "brideRole", "closingFam", "closingThanks", "countdownMaster", "coupleSub", "coupleTitle", "createdAt", "dateText", "gal1", "gal2", "gal3", "gal4", "gal5", "gal6", "groomDad", "groomFull", "groomMom", "groomNick", "groomPhoto", "groomRole", "id", "name", "resepsiDate", "resepsiPlace", "resepsiTime", "rsvpDesc", "rsvpTitle", "status", "storyDate1", "storyDate2", "storyDesc1", "storyDesc2", "storyTitle1", "storyTitle2", "streamDesc", "streamTitle", "templateId", "updatedAt", "verseSource", "verseText", "wishesDesc", "wishesTitle" FROM "Customer";
DROP TABLE "Customer";
ALTER TABLE "new_Customer" RENAME TO "Customer";
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
